//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mvcapi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class WorkDescription
    {
        public int id { get; set; }
        public string projecttitle { get; set; }
        public string projectdescription { get; set; }
        public Nullable<System.DateTime> projectcreateddate { get; set; }
        public Nullable<System.DateTime> addedon { get; set; }
        public string projectdevelopers { get; set; }
        public Nullable<bool> isexternal { get; set; }
    }
}
